import type { TrainingConfig } from "../types";
import type { TrainerField, TrainerSection } from "./types";

type F = TrainerField<TrainingConfig>;
const text = (key: F["key"], label: string, hint?: string): F => ({ key, label, kind: "text", hint });
const num = (key: F["key"], label: string, min = 0, hint?: string): F => ({ key, label, kind: "number", min, hint });
const toggle = (key: F["key"], label: string, hint?: string): F => ({ key, label, kind: "toggle", hint });
const select = (key: F["key"], label: string, options: F["options"], hint?: string): F => ({
  key, label, kind: "select", options, hint,
});
const file = (key: F["key"], label: string, extensions?: string[]): F => ({ key, label, kind: "file", extensions });
const dir = (key: F["key"], label: string): F => ({ key, label, kind: "directory" });

const scriptOptions = [
  { value: "train_network.py", label: "SD 1.x / 2.x — train_network.py" },
  { value: "sdxl_train_network.py", label: "SDXL — sdxl_train_network.py" },
  { value: "anima_train_network.py", label: "Anima — anima_train_network.py" },
];

export const sdScriptsSections: TrainerSection<TrainingConfig>[] = [
  {
    id: "model",
    title: "模型与脚本",
    description: "模型来源、训练脚本、VAE 与文本编码器。",
    fields: [
      select("trainingScript", "训练脚本", scriptOptions),
      file("pretrainedModel", "预训练模型", ["safetensors", "ckpt", "pt"]),
      file("vae", "VAE", ["safetensors", "pt", "pth"]),
      file("animaQwen3", "Anima Qwen3 文本编码器", ["safetensors"]),
      text("animaLlmAdapterLr", "Anima LLM Adapter LR"),
      num("clipSkip", "Clip Skip"),
      toggle("v2", "Stable Diffusion v2"),
      toggle("vParameterization", "V 参数化训练"),
      dir("tokenizerCacheDir", "Tokenizer 缓存目录"),
      toggle("noHalfVae", "VAE 强制 float32"),
    ],
  },
  {
    id: "network",
    title: "LoRA / Network",
    fields: [
      text("networkModule", "Network Module", "留空时按脚本自动选择 networks.lora / networks.lora_anima"),
      num("networkDim", "Network Dim / Rank", 1),
      num("networkAlpha", "Network Alpha", 0),
      num("convDim", "Conv Dim"),
      num("convAlpha", "Conv Alpha"),
      text("networkDropout", "Network Dropout"),
      text("networkArgs", "Network Args", "空格分隔 key=value；与 Conv 参数合并"),
      file("networkWeights", "初始化 Network 权重", ["safetensors", "pt"]),
      toggle("dimFromWeights", "从权重自动读取 Rank"),
      text("scaleWeightNorms", "Scale Weight Norms"),
      toggle("networkTrainUnetOnly", "仅训练 U-Net"),
      toggle("networkTrainTextEncoderOnly", "仅训练文本编码器"),
      text("baseWeights", "训练前合并的 Base Weights", "多个路径用空格分隔"),
      text("baseWeightsMultiplier", "Base Weights Multiplier", "与 Base Weights 一一对应"),
      text("trainingComment", "训练备注（写入元数据）"),
      toggle("noMetadata", "不保存元数据"),
    ],
  },
  {
    id: "training",
    title: "训练循环",
    fields: [
      text("resolution", "训练分辨率", "如 1024x1024 或 768,1344"),
      num("batchSize", "Batch Size", 1),
      num("gradientAccumulationSteps", "梯度累积步数", 1),
      select("trainingLengthMode", "训练长度单位", [
        { value: "steps", label: "Steps" }, { value: "epochs", label: "Epochs" },
      ]),
      num("maxTrainSteps", "最大训练步数", 1),
      num("epochs", "训练 Epochs", 1),
      num("seed", "随机种子"),
      num("initialEpoch", "初始 Epoch"),
      num("initialStep", "初始 Step"),
      toggle("skipUntilInitialStep", "跳过数据直到 Initial Step"),
      file("resume", "恢复训练 State"),
      num("maxDataLoaderWorkers", "DataLoader Workers"),
      toggle("persistentDataLoaderWorkers", "持久化 DataLoader Workers"),
    ],
  },
  {
    id: "optimizer",
    title: "优化器与学习率",
    fields: [
      text("optimizer", "Optimizer Type", "支持类全路径及 sd-scripts 的全部优化器"),
      text("optimizerArgs", "Optimizer Args", "空格分隔 key=value"),
      text("baseLr", "基础学习率"),
      text("unetLr", "U-Net LR"),
      text("textEncoderLr", "Text Encoder LR", "多个编码器可用空格分隔"),
      text("lrScheduler", "LR Scheduler"),
      text("lrSchedulerType", "自定义 Scheduler Module"),
      text("lrSchedulerArgs", "Scheduler Args"),
      num("lrWarmupSteps", "Warmup Steps"),
      text("lrDecaySteps", "LR Decay Steps / Ratio"),
      text("lrSchedulerNumCycles", "Scheduler Cycles"),
      text("lrSchedulerPower", "Scheduler Power"),
      text("lrSchedulerTimescale", "Inverse Sqrt Timescale"),
      text("lrSchedulerMinLrRatio", "最小 LR Ratio"),
      text("maxGradNorm", "Max Grad Norm"),
      toggle("fusedBackwardPass", "Fused Backward Pass"),
    ],
  },
  {
    id: "precision-memory",
    title: "精度、显存与编译",
    fields: [
      select("mixedPrecision", "混合精度", ["no", "fp16", "bf16"]),
      select("savePrecision", "保存精度", ["", "float", "fp16", "bf16"]),
      select("saveModelAs", "保存格式", ["safetensors", "ckpt", "pt"]),
      toggle("fullFp16", "Full FP16"),
      toggle("fullBf16", "Full BF16"),
      toggle("fp8Base", "FP8 Base Model"),
      toggle("fp8BaseUnet", "FP8 U-Net / DiT"),
      toggle("gradientCheckpointing", "梯度检查点"),
      toggle("cpuOffloadCheckpointing", "检查点张量卸载到 CPU"),
      toggle("xformers", "xFormers Attention"),
      toggle("sdpa", "PyTorch SDPA"),
      toggle("memEffAttn", "Memory Efficient Attention"),
      toggle("torchCompile", "torch.compile"),
      select("dynamoBackend", "Dynamo Backend", [
        "inductor", "eager", "aot_eager", "cudagraphs", "onnxrt", "tvm",
      ]),
      toggle("lowram", "Low RAM 模式"),
      toggle("highvram", "High VRAM 模式"),
      num("blocksToSwap", "Blocks To Swap"),
    ],
  },
  {
    id: "cache",
    title: "缓存",
    fields: [
      toggle("cacheLatents", "缓存 Latents"),
      toggle("cacheLatentsToDisk", "Latents 缓存到磁盘"),
      num("vaeBatchSize", "VAE 缓存 Batch Size", 1),
      toggle("skipCacheCheck", "跳过缓存内容校验"),
      toggle("cacheTextEncoderOutputs", "缓存文本编码器输出"),
      toggle("cacheTextEncoderOutputsToDisk", "文本编码器输出缓存到磁盘"),
      num("textEncoderBatchSize", "文本编码器 Batch Size"),
      toggle("disableMmapLoadSafetensors", "禁用 safetensors mmap"),
    ],
  },
  {
    id: "loss-noise",
    title: "损失、噪声与时间步",
    fields: [
      text("minSnrGamma", "Min SNR Gamma"),
      text("noiseOffset", "Noise Offset"),
      toggle("noiseOffsetRandomStrength", "Noise Offset 随机强度"),
      num("multiresNoiseIterations", "Multi-resolution Noise Iterations"),
      text("multiresNoiseDiscount", "Multi-resolution Noise Discount"),
      text("ipNoiseGamma", "Input Perturbation Noise Gamma"),
      toggle("ipNoiseGammaRandomStrength", "IP Noise 随机强度"),
      text("adaptiveNoiseScale", "Adaptive Noise Scale"),
      toggle("zeroTerminalSnr", "Zero Terminal SNR"),
      num("minTimestep", "最小 Timestep"),
      num("maxTimestep", "最大 Timestep"),
      select("lossType", "Loss Type", ["l1", "l2", "huber", "smooth_l1"]),
      select("huberSchedule", "Huber Schedule", ["constant", "exponential", "snr"]),
      text("huberC", "Huber C"),
      text("huberScale", "Huber Scale"),
      text("priorLossWeight", "Prior Loss Weight"),
      select("weightingScheme", "DiT Timestep Weighting", [
        "uniform", "none", "sigma_sqrt", "logit_normal", "mode", "cosmap",
      ]),
      text("logitMean", "Logit Mean"),
      text("logitStd", "Logit Std"),
      text("modeScale", "Mode Scale"),
      toggle("maskedLoss", "Masked Loss"),
      dir("conditioningDataDir", "Conditioning / Mask 数据目录"),
      toggle("trainInpainting", "训练 Inpainting"),
    ],
  },
  {
    id: "dataset",
    title: "数据集与 Caption",
    fields: [
      num("datasetRepeats", "数据集重复次数", 1),
      toggle("enableBucket", "启用分辨率 Bucket"),
      num("minBucketReso", "最小 Bucket 分辨率"),
      num("maxBucketReso", "最大 Bucket 分辨率"),
      num("bucketResoSteps", "Bucket 分辨率步长", 1),
      toggle("bucketNoUpscale", "Bucket 不放大图片"),
      select("resizeInterpolation", "缩放插值", ["", "lanczos", "nearest", "bilinear", "bicubic", "area"]),
      text("skipImageResolution", "跳过不大于此分辨率的图片"),
      toggle("shuffleCaptions", "Shuffle Caption"),
      text("captionSeparator", "Caption 分隔符"),
      num("keepTokens", "Keep Tokens"),
      text("keepTokensSeparator", "Keep Tokens 分隔符"),
      text("secondarySeparator", "Secondary Separator"),
      toggle("enableWildcard", "启用 Caption Wildcard"),
      text("captionPrefix", "Caption Prefix"),
      text("captionSuffix", "Caption Suffix"),
      text("captionDropoutRate", "Caption Dropout Rate"),
      num("captionDropoutEveryNEpochs", "每 N Epoch 丢弃全部 Caption"),
      text("captionTagDropoutRate", "Caption Tag Dropout Rate"),
      toggle("colorJitter", "颜色增强"),
      toggle("flipAug", "水平翻转增强"),
      text("faceCropAugRange", "人脸中心裁剪范围"),
      toggle("randomCrop", "随机裁剪"),
      num("tokenWarmupMin", "Token Warmup 起始标签数"),
      text("tokenWarmupStep", "Token Warmup Step / Ratio"),
      toggle("alphaMask", "使用 Alpha 通道作为 Mask"),
    ],
  },
  {
    id: "saving",
    title: "保存与恢复",
    fields: [
      num("saveEveryNEpochs", "每 N Epoch 保存"),
      num("saveEveryNSteps", "每 N Step 保存"),
      num("saveNEpochRatio", "保存 Epoch 比例"),
      num("saveLastNEpochs", "保留最近 N 个 Epoch 模型"),
      num("saveLastNEpochsState", "保留最近 N 个 Epoch State"),
      num("saveLastNSteps", "保留最近 N Steps 模型"),
      num("saveLastNStepsState", "保留最近 N Steps State"),
      toggle("saveState", "保存训练 State"),
      toggle("saveStateOnTrainEnd", "结束时保存 State"),
    ],
  },
  {
    id: "validation-sampling",
    title: "验证与采样",
    fields: [
      text("validationSplit", "验证集比例"),
      num("validationSeed", "验证集随机种子"),
      num("validateEveryNSteps", "每 N Step 验证"),
      num("validateEveryNEpochs", "每 N Epoch 验证"),
      num("maxValidationSteps", "最大验证步数"),
      { ...text("samplePrompts", "采样提示词（每行一个）"), kind: "textarea", wide: true },
      { ...text("sampleNegativePrompt", "采样负向提示词"), kind: "textarea", wide: true },
      num("sampleEveryNSteps", "每 N Step 采样"),
      num("sampleEveryNEpochs", "每 N Epoch 采样"),
      toggle("sampleAtFirst", "训练前采样"),
      text("sampleSampler", "采样器"),
      num("sampleWidth", "采样宽度", 1),
      num("sampleHeight", "采样高度", 1),
      num("sampleSteps", "采样步数", 1),
      text("sampleCfgScale", "采样 CFG Scale"),
      num("sampleSeed", "采样种子"),
    ],
  },
  {
    id: "monitoring",
    title: "训练监控",
    fields: [
      dir("loggingDir", "日志目录"),
      select("logWith", "日志后端", ["", "tensorboard", "wandb", "all"]),
      text("logPrefix", "日志目录前缀"),
      text("logTrackerName", "Tracker 名称"),
      text("wandbRunName", "WandB Run 名称"),
      text("wandbApiKey", "WandB API Key"),
      toggle("logConfig", "记录训练配置"),
    ],
  },
];
